version: '3.5'
services:

  galileo:
    build: galileo
    ports:
      - 3000:3000
    command: galileo setup

  nginx:
    image: nginx:latest

  zap:
    image: owasp/zap2docker-bare
  # zaproxy:
  #   image: owasp/zap2docker-stable
    command: zap.sh -daemon -port 8090 -host 0.0.0.0
    expose:
    # ZAP is running on 8090, we want it to be accessible by our tools
      - "8090"
    ports:
      - 8090:8090
    links:
      - target

  target:
    # The target application we want to scan
    image: szsecurity/webgoat
    # The port that the application is available on.
    # If the application runs on a non-standard port,
    # you can map it to 80 for convenience by using
    ports:
     - "80:80"
    expose:
      - "80"



  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example