dist: xenial
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-bibtex-extra
  biber
script:
- make
deploy:
  provider: releases
  api_key: $GH_TOKEN
    # secure: FQcp/Qnme0MHgosH5NShQhFsScwL0kz52B/q2C2WiB2ygN/2hw0VQOiT+rgFSHWyKKo6wcePf88nP5T2adoxsijdu8jfGjPvXgC30U0MTp86n+XJMZpUoOXXSbwr0JZyB8hivvso/CH/yw81uLbbu6WDWjyTBIydBYiPacCYRRd/ATf5zDIs/Q3hUroGWR/6RDAlI00bdTmWM3ds0fLUDYHHNSxcq56sdtEkpqC3qz31roNDN8gRZwK4PiAtkttDXNDXGgE7xqdEumTGKz4EAzeu4gOxzG9qo7SxmyiVSU81kNPnqOJ1UF+7FaBzbpsYJnRPPXPzAsuUDb9axBahR4PtQVCuVPuxZMUgtT5EpQt3E/TYoGrhSOpGpRR274WS45hD3Pk0mF/fkqW5naJQK0tYiAA3AVuk3i1F0lB6sG+nHtdeU0DtQLg6p3laN/wT0HqP9+JiToO5oo6/mDhcSE9pf9xyn904s794PjW7GcOAFp9stPrL9Wu2EqzQi3JlqyPErVq9ohry8jday+a+PjwGYYYBbrgDCN69ENs2WbR9Gje/lRByJu+vhu05uKXHEjEzWowdMkH+hfrSluYWAk78ybHMApEzUd/KkQQ7AzXdMIUXYrGTEd6p/rUR6lyZ8poOvTqRmrzJOUpUnDbG4zypOmxbMZLZnEcQY3kvMCE=
  file: project.pdf
  skip_cleanup: true
  on:
    repo: erseco/moving_target_defense
    tags: true