name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        cd code
        docker-compose build
        docker-compose up -d
        sleep 40
        docker-compose exec -T www.exampletfm.com python3 genetic.py
